global TIME_INQUIRE_REPORT_DELAY_SEC
TIME_INQUIRE_REPORT_DELAY_SEC = 0.130

global TIME_OPEN_BROWSER_SEC
TIME_OPEN_BROWSER_SEC = 0.2

global TIME_SEND_REPORT_DELAY_SEC
TIME_SEND_REPORT_DELAY_SEC = 0.7

